[project]
name = "uv2nix-bootstrap"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "uvicorn[standard]>=0.35.0",
]

[project.scripts]
run-server = "main:run_server"
